import {PROJECT_NAME}Core

do {
    try {PROJECT_NAME}().run()
} catch {
    print("An error occurred: \(error)")
}
